Countries = ['Morocco', 'Algerie', 'United states', 'Japan']
print(Countries)
Countries.insert(0, 'Libye')
Countries.insert(3, 'Tunisie')
Countries.append('Suisse')
Countries.pop()
Countries.remove("Tunisie")
del Countries[0]
print(Countries)
print("+==============================================+")
print(sorted(Countries))
print(sorted(Countries, reverse= True))
Countries.reverse()
print(Countries)
Countries.sort()
print(Countries)
Countries.sort(reverse = True)
print(Countries)
print("+==============================================+")
