names = ['Muhamed', 'Hachim', 'Mansour', 'Ali']
names.insert(0, 'Hamza')
names.insert(3, 'Othmane')
names.append('Adnane')
print(f"{names[0].title()}, you are invite to dinner")
print(f"{names[1].title()}, you are invite to dinner")
print(f"{names[2].title()}, you are invite to dinner")
print(f"{names[3].title()}, you are invite to dinner")
print(f"{names[4].title()}, you are invite to dinner")
print(f"{names[5].title()}, you are invite to dinner")
print(f"{names[6].title()}, you are invite to dinner")