City = ['Mecca', 'Dubai', 'Tokyo', 'Berne', 'Moscou']
print(City)
print(sorted(City))
print(City)
print(sorted(City, reverse = True))
print(City)
print("+================+")
City.reverse()
print(City)
City.reverse()
print(City)
print("+================+")
City.sort()
print(City)
City.sort(reverse = True)
print(City)